---
title: "Hugo Zen theme"
baseURL: "https://example.org/"
theme: "zen"
languageCode: "en-GB"
#defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Your Name"
  url: "https://example.org/somepage"
  avatar: "path/to/some-image.jpg"

outputs:
  home: ["HTML","RSS", "JSON"]
  section: ["HTML","RSS", "JSON"]

#languages:
#  en:
#    contentdir: "content/english"
#    languagename: "English"
#  de:
#    contentdir: "content/deutsch"
#    languagename: "Deutsch"

params:
  contact: "info@example.org"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The zen theme for Hugo example site."
  dateformat: "2 January, 2006"
  header_site_name: false
  favicon: "apple-touch-icon.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  logo_path: "/images/logo.png"
  mobileMenu: true
  poweredby: false
  search: true
  searchSize: 20
  sidebar: true
  slogan: "Jsme hnutí usilující o ukončení těžby a spalování fosilních paliv.<br>Naším cílem je klimatická spravedlnost."
  header_action_links:
    join-us:
        text: "Přidej se k nám"
        url: "/join-us"
    learn-more:
        text: "Chci vědět víc"
        url: "/o-nas"
  submitted: true
  topbar: true
  socialprofiles:
    facebook: "https://facebook.com"
    twitter: "https://twitter.com"
    instagram: "https://instagram.com"
